#!/usr/bin/env python3
"""regenerate_test_catalog.py — refresh tests/CATALOG.md from test docstrings.

Plan §15.5.12: a future agent should be able to answer "what tests exist?"
in under 60 seconds. The catalog is auto-generated so it never goes stale.

The pre-push hook calls this with --check; it exits non-zero if the catalog
on disk doesn't match what would be regenerated. CI calls it the same way.

Usage:
    python scripts/regenerate_test_catalog.py            # rewrite the file
    python scripts/regenerate_test_catalog.py --check    # verify only

Layout written:
    # Test Catalog — Clinical Co-Pilot
    ## Last regenerated: <ISO date>
    ## L1 — Pure unit
    ## L2 — Integration
    ## L3 — End-to-end
    ## L4 — Eval cases
    ## L5 — Live-vendor smoke

Each entry's first line is the docstring's first paragraph (one sentence).
"""

from __future__ import annotations

import argparse
import ast
import datetime
import json
import pathlib
import sys
from typing import Iterable


REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
SIDECAR = REPO_ROOT / "agent" / "copilot-api"
CATALOG = SIDECAR / "tests" / "CATALOG.md"

LAYER_DIRS = [
    ("L1 — Pure unit", SIDECAR / "tests" / "unit"),
    ("L2 — Integration", SIDECAR / "tests" / "integration"),
    ("L3 — End-to-end", SIDECAR / "tests" / "e2e"),
]


def _module_first_line(path: pathlib.Path) -> str:
    """Return the first non-empty line of the module docstring, or a placeholder."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except Exception:
        return "(could not parse)"
    doc = ast.get_docstring(tree) or ""
    for line in doc.splitlines():
        s = line.strip()
        if s:
            return s
    return "(no module docstring)"


def _iter_tests(directory: pathlib.Path) -> Iterable[pathlib.Path]:
    if not directory.exists():
        return []
    return sorted(p for p in directory.glob("test_*.py") if p.is_file())


def _eval_cases() -> list[tuple[str, str, str]]:
    """Return (category, file_relpath, what_bug_this_catches) per case."""
    cases_dir = SIDECAR / "evals" / "cases"
    if not cases_dir.exists():
        return []
    rows: list[tuple[str, str, str]] = []
    for sub in sorted(cases_dir.iterdir()):
        if sub.is_dir():
            for case in sorted(sub.glob("*.json")):
                rows.append(_load_case_row(case, sub.name))
        elif sub.suffix == ".json":
            # Wk1-flat layout
            rows.append(_load_case_row(sub, "wk1"))
    return rows


def _load_case_row(case: pathlib.Path, category: str) -> tuple[str, str, str]:
    try:
        data = json.loads(case.read_text(encoding="utf-8"))
        what = data.get("what_bug_this_catches") or data.get("description") or "—"
    except Exception as e:
        what = f"(parse error: {e})"
    return (category, str(case.relative_to(SIDECAR)), what)


def _live_smoke_cases() -> list[tuple[str, str]]:
    smoke = SIDECAR / "evals" / "live_smoke"
    if not smoke.exists():
        return []
    return [(p.name, _load_case_row(p, "live_smoke")[2]) for p in sorted(smoke.glob("*.json"))]


def render() -> str:
    out: list[str] = []
    out.append("<!-- AUTO-GENERATED by scripts/regenerate_test_catalog.py — do not edit by hand. -->")
    out.append("# Test Catalog — Clinical Co-Pilot\n")
    out.append("This catalog is auto-generated from test module docstrings and eval-case `what_bug_this_catches` fields.")
    out.append("See Plan §15.5.12 (freshness check) and the `testing-discipline-clinical-copilot` skill.\n")
    out.append(f"## Last regenerated\n\n{datetime.date.today().isoformat()}\n")

    for layer_name, layer_dir in LAYER_DIRS:
        out.append(f"## {layer_name} (`{layer_dir.relative_to(REPO_ROOT)}/`)\n")
        files = list(_iter_tests(layer_dir))
        if not files:
            out.append("*(empty — populated as Teams A/B/C land tests)*\n")
            continue
        for f in files:
            out.append(f"- **{f.name}** — {_module_first_line(f)}")
        out.append("")

    # Wk1-style flat tests/test_*.py (still in scope)
    flat_tests = sorted((SIDECAR / "tests").glob("test_*.py"))
    if flat_tests:
        out.append("## Wk1 unit tests (still in scope, pre-pyramid layout)\n")
        for f in flat_tests:
            out.append(f"- **{f.name}** — {_module_first_line(f)}")
        out.append("")

    out.append("## L4 — Eval cases (`evals/cases/`)\n")
    cases = _eval_cases()
    if not cases:
        out.append("*(empty — populated as cases land)*\n")
    else:
        out.append("| Category | File | What bug this catches |")
        out.append("|---|---|---|")
        for cat, path, what in cases:
            esc_what = what.replace("|", "\\|").replace("\n", " ")
            esc_path = path.replace("|", "\\|")
            out.append(f"| `{cat}` | `{esc_path}` | {esc_what} |")
        out.append("")

    out.append("## L5 — Live-vendor smoke (`evals/live_smoke/`)\n")
    smoke = _live_smoke_cases()
    if not smoke:
        out.append("*(empty — populated by Workstream C; nightly only, never PR-blocking)*\n")
    else:
        for name, what in smoke:
            esc_what = what.replace("|", "\\|").replace("\n", " ")
            out.append(f"- **{name}** — {esc_what}")
        out.append("")

    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify only (exit 1 if stale)")
    args = parser.parse_args()

    new = render()
    if args.check:
        existing = CATALOG.read_text(encoding="utf-8") if CATALOG.exists() else ""
        if existing.strip() != new.strip():
            print(
                "tests/CATALOG.md is stale — run `python scripts/regenerate_test_catalog.py`",
                file=sys.stderr,
            )
            return 1
        print("tests/CATALOG.md is up to date")
        return 0

    CATALOG.write_text(new, encoding="utf-8")
    print(f"wrote {CATALOG}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
