"""Query rewriter for clinical-synonym expansion (AgDR-0085, Plan §7.2.c).

``expand_query(query)`` returns the original query plus up-to-4 deterministic
paraphrases generated by substituting one synonym per pass. The first
element is always the original query — callers can iterate the list and
RRF-fuse the per-paraphrase retrieval results without special-casing
"the original is also a paraphrase."

Why deterministic-first: the LLM-fallback path (>10-word queries or
queries with zero synonym hits) is scaffolded but NOT enabled in Wk2 —
adding a Haiku call to the critical retrieval path costs latency budget
that Wk2 doesn't have, and the eval suite covers the deterministic
expander adequately. Wk3 wires the LLM fallback behind a feature flag.

Cap rationale: 5 total queries (original + 4 paraphrases) keeps the
per-question retrieval budget at 5 * (BM25 + vector) ≈ 10 SQL calls, which
is well under the p95 latency floor. RRF naturally weights overlap so
running 5 paraphrases of "Is her A1c controlled?" doesn't 5x the cost of
a single-query path — it just reranks the same candidate pool.
"""

from __future__ import annotations

import logging
import re
from typing import Iterable

from .synonyms import variants_for

logger = logging.getLogger(__name__)

MAX_PARAPHRASES = 5
LLM_FALLBACK_WORD_THRESHOLD = 10

_TOKEN_RE = re.compile(r"\b[A-Za-z][A-Za-z0-9-]*\b")


def _tokenize_with_positions(query: str) -> list[tuple[int, int, str]]:
    """Return [(start, end, token_text), ...] preserving byte offsets so the
    rewriter can substitute in place without disturbing punctuation or
    word order."""
    return [(m.start(), m.end(), m.group(0)) for m in _TOKEN_RE.finditer(query)]


def _substitute(query: str, start: int, end: int, replacement: str) -> str:
    """Replace ``query[start:end]`` with ``replacement`` preserving the rest."""
    return query[:start] + replacement + query[end:]


def expand_query(
    query: str, *, max_paraphrases: int = MAX_PARAPHRASES
) -> list[str]:
    """Expand *query* into a list of up-to-*max_paraphrases* paraphrases.

    The first element is always the original query (verbatim). Subsequent
    elements substitute ONE token at a time with one of its synonyms,
    preserving the rest of the query.

    Substitution order is **round-robin across tokens**: round 1 emits the
    first variant of every synonymable token (left-to-right by token
    position), round 2 emits the second variant of every token, and so on.
    This guarantees broader query coverage than a greedy-leftmost approach
    would — for "Is her A1c affected by warfarin dosing?" round-robin
    produces one A1c-swap AND one warfarin-swap before stacking second
    variants of A1c, whereas a greedy approach would consume all 5
    paraphrase slots on A1c variants and never reach warfarin. The cost
    is the same; only the order differs.

    Empty input returns ``[""]`` so downstream code never sees an empty
    list. The original is always position 0 even if no synonyms match.
    """
    if max_paraphrases < 1:
        max_paraphrases = 1
    out: list[str] = [query]
    if not query.strip():
        return out

    tokens = _tokenize_with_positions(query)
    if not tokens:
        return out

    # Build per-token substitution lists (excluding the variant that would
    # reproduce the original token). Tokens with no synonym hits are dropped
    # entirely so the round-robin doesn't waste slots on them.
    token_subs: list[list[tuple[int, int, str]]] = []
    for start, end, token_text in tokens:
        variants = variants_for(token_text)
        if variants is None:
            continue
        extras = [v for v in variants if v != token_text.lower()]
        if extras:
            token_subs.append([(start, end, v) for v in extras])

    if not token_subs:
        return out

    seen: set[str] = {query.lower()}
    max_rounds = max(len(lst) for lst in token_subs)
    for round_idx in range(max_rounds):
        for subs in token_subs:
            if round_idx >= len(subs):
                continue
            start, end, variant = subs[round_idx]
            candidate = _substitute(query, start, end, variant)
            key = candidate.lower()
            if key in seen:
                continue
            out.append(candidate)
            seen.add(key)
            if len(out) >= max_paraphrases:
                return out
    return out


def should_use_llm_fallback(query: str) -> bool:
    """Heuristic: complex queries (>``LLM_FALLBACK_WORD_THRESHOLD`` words)
    OR queries with zero synonym hits benefit from an LLM-paraphrase pass.

    Gated on a feature flag in callers; this function just answers the
    classification question deterministically so the call site reads
    cleanly.
    """
    word_count = len(query.split())
    if word_count > LLM_FALLBACK_WORD_THRESHOLD:
        return True
    tokens = _tokenize_with_positions(query)
    return all(variants_for(t[2]) is None for t in tokens)


def expand_query_with_llm_fallback(
    query: str,
    *,
    llm_paraphraser: "Callable[[str], Iterable[str]] | None" = None,  # type: ignore[name-defined]
    max_paraphrases: int = MAX_PARAPHRASES,
) -> list[str]:
    """Wrapper that adds LLM-generated paraphrases when the heuristic fires.

    ``llm_paraphraser`` is injected (deterministic mock in eval mode, real
    Haiku call in live mode) — keeps the rewriter free of vendor-SDK
    imports. Returns the deterministic expansion when ``llm_paraphraser``
    is None or when the heuristic doesn't fire.

    Wk3 wires the real Haiku 4.5 caller; Wk2 ships with this scaffold and
    the feature flag default OFF (no callers pass an llm_paraphraser).
    """
    out = expand_query(query, max_paraphrases=max_paraphrases)
    if llm_paraphraser is None or not should_use_llm_fallback(query):
        return out
    if len(out) >= max_paraphrases:
        return out
    try:
        for extra in llm_paraphraser(query):
            extra_norm = extra.strip()
            if not extra_norm:
                continue
            if extra_norm.lower() in {p.lower() for p in out}:
                continue
            out.append(extra_norm)
            if len(out) >= max_paraphrases:
                break
    except Exception as exc:  # noqa: BLE001 — fallback must never raise
        logger.warning("LLM paraphraser failed (%s) — using deterministic only", exc)
    return out
